"""add version

Revision ID: 0e68f32d16bc
Revises: d3545671fa7f
Create Date: 2019-03-11 02:15:27.830841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e68f32d16bc'
down_revision = 'd3545671fa7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(length=512), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('max_ver', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('versions')
    # ### end Alembic commands ###
