"""init_db

Revision ID: 999bd8686f37
Revises: 
Create Date: 2020-07-21 16:08:54.058017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999bd8686f37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storages',
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('root', sa.String(length=256), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('modules',
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('storage_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['storage_id'], ['storages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lambdas',
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('dtype', sa.String(length=8), nullable=True),
    sa.Column('adapted', sa.Boolean(), nullable=True),
    sa.Column('atomic', sa.Boolean(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('python_version', sa.String(length=8), nullable=True),
    sa.Column('python_packages', sa.Text(), nullable=True),
    sa.Column('sql_url', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variables',
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('asc', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('as_primary', sa.Boolean(), nullable=True),
    sa.Column('as_oid', sa.Boolean(), nullable=True),
    sa.Column('as_time', sa.Boolean(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('stateful', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scope_id'], ['lambdas.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['lambdas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variables')
    op.drop_table('scripts')
    op.drop_table('lambdas')
    op.drop_table('modules')
    op.drop_table('storages')
    # ### end Alembic commands ###
